openapi: 3.0.3
info:
  title: Library API
  version: 1.1.1
  description: STD22103
servers:
  - url: https://library.com
tags:
  - name: Books  
  - name: Authors
  - name: Import
paths:
  /books:
    get:
      summary: Get all books
      description: The returned books are ordered by updated datetime.
      operationId: getBooks
      tags:
        - Books
      parameters:
        - in: query
          name: bookName
          description: Filter return books by given name
          required: false
          schema:
            type: string
        - name: startDate
          in: query
          description: the starting date
          required: false
          schema: 
            type: string
            format: date
        - name: finalDate
          in: query
          description: the ending date
          required: false
          schema: 
            type: string
            format: date
        - $ref: "#/components/parameters/queryPagination"
      responses:
        200:
          description: List of ordered books
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
    put:
      summary: Create or update a list of books
      operationId: crupdateBooks
      tags:
        - Books
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated books
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
  /authors:
    get:
      summary: Get all authors 
      description: The returned authors are ordered by name 
      operationId: getAuthors
      tags:
        - Authors
      parameters:
        - in: query
          name: name
          description: filter authors by name
          required: false
          schema: 
            type: string
      responses:
        200: 
          description: list of filter author 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
    put:
      summary: Create or update an author
      operationId: crupdateAuthor
      tags:
        - Authors
      requestBody: 
        content:
          application/json:
            schema: 
              type: array
              items:
                $ref: '#/components/schemas/Author'
      responses:
        200:
          $ref: "#/components/schemas/Response200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
  /authors/{id}:
    delete:
      summary: Delete an author
      description: Delete an author by id 
      operationId: deleteAuthor
      tags:
        - Authors
      parameters:
        - name: id 
          in: path
          required: true
          schema: 
            type: string
      responses:
        200:
          description: An author deleted
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
  /multipleDelete:
    delete: 
      summary: Delete multiple authors
      description: Delete multiple authors by their ids
      requestBody: 
        content:
          application/json: 
            schema: 
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: string
      responses:
        200:
          description: Multiple authors deleted
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
  /authors/{pathPagination}:
    get:
      summary: Get all authors
      operationId: getAuthorsPagination
      tags:
        - Authors
      parameters:
        - $ref: "#/components/parameters/pathPagination"
      responses: 
        200:
          description: List of all authors
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
        
  /books/{bookId}/authors/{authorId}:
    put:
      tags:
        - Books
      parameters:
        - name: bookId
          in: path
          schema: 
            type: string
          required: true
      responses:
        200:
          description: The updated book with author
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
  /books/authors: 
    put:
      tags:
        - Books
      operationId: updateBookAuthor 
      requestBody:
        content:
          application/json:
            schema: 
              type: array
              items: 
                $ref: "#/components/schemas/UpdateBookAuthor"  
      responses:
        200:
          description: The updated book with the author
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response200"   
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403" 
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
  /books/import:
    post:
      summary: Import books from Excel or JSON
      tags:
        - Import
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Book"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: object  
        description: book files (Excel or JSON)
      responses:
        200:
          description: Books imported
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
  /authors/import:
    post:
      summary: Import authors from Excel or JSON
      tags:
        - Import
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Author"
          application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
            schema:
              type: object  
        description: auhtors files (JSON or Excel)
      responses:
        200:
          description: Authors imported
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Response200"
        400: 
          description: 400 bad request
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status400"
        403: 
          description: 403 Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status403"
        500: 
          description: 500 Internal server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Status500"
    
components:
  schemas:
    Book:
      allOf:
        - $ref: "#/components/schemas/CrupdateBook"
        - type: object
          properties:
            author: 
              $ref: "#/components/schemas/Author"
    Author: 
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          type: string
          enum:
            - F
            - M
    CrupdateBook:
      type: object
      properties:
        id:
          type: string
        bookName:
          type: string
        pageNumbers:
          type: integer
        topic:
          type: string
          enum:
            - ROMANCE
            - COMEDY
            - OTHER
        releaseDate:
          type: string
          format: date
    UpdateBookAuthor:
      type: object
      properties:
        bookId:
          type: string
        authorId:
          type: string
      required:
        - bookId
        - authorId
    Response: 
      type: object
      properties:
        body: 
          $ref: "#/components/schemas/Body"
    Response200: 
      allOf:
        - $ref: "#/components/schemas/Response"
          type: object
          description: Operation successful
          properties:
            status200: 
              $ref: "#/components/schemas/Status200"
    Response400: 
      allOf:
        - $ref: "#/components/schemas/Response"
          type: object
          description: Bad request
          properties:
            status200: 
              $ref: "#/components/schemas/Status400"
    Response403: 
      allOf:
        - $ref: "#/components/schemas/Response"
          type: object
          description: Forbidden
          properties:
            status200: 
              $ref: "#/components/schemas/Status403"
    Response500: 
      allOf:
        - $ref: "#/components/schemas/Response"
          type: object
          description: Forbidden
          properties:
            status200: 
              $ref: "#/components/schemas/Status500"              
    Status200: 
      type: object
      properties:
        code: 
          example: 200
        message:
          example: "OK"
    Status400: 
      type: object
      properties:
        code: 
          example: 400
        message:
          example: "Bad request"
    Status403: 
      type: object
      properties:
        code: 
          example: 403
        message:
          example: "Forbidden"
    Status500: 
      type: object
      properties:
        code: 
          example: 500
        message:
          example: "Internal server error"
    Body: 
      type: object
      oneOf:
        - $ref: "#/components/schemas/Book"
        - $ref: "#/components/schemas/Books"
        - $ref: "#/components/schemas/Author"
        - $ref: "#/components/schemas/Authors"
    Books: 
      type: array
      items: 
        $ref: "#/components/schemas/Book"
    Authors: 
      type: array
      items: 
        $ref: "#/components/schemas/Author" 
  parameters:
    QueryPage:
      name: queryPage 
      in: query
      required:  false
      schema: 
        type: integer
        default: 1
    QueryPageSize:
      name: queryPageSize
      in: query
      required:  false
      schema: 
        type: integer
        default: 50
    pathPage: 
      name: pathPage
      in: path
      required: false
      schema: 
        type: integer
        default: 1
    pathPageSize: 
      name: pathPage
      in: path
      required: false
      schema: 
        type: integer
        default: 50
